// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fioxfwmcoylpszgreteo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpb3hmd21jb3lscHN6Z3JldGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4OTkwMTksImV4cCI6MjA3MjQ3NTAxOX0.IDMJungxph8RVtXf4RePsFcgXZdqn8PshR6797Ohrqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});